
GET https://localhost:3000/api/staff
Content-Type: application/json
Authorization: "bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NWVkY2ZlODU4MGE2ZWY1MmE5NjE2OCIsImlhdCI6MTcxODI0MTcyOCwiZXhwIjoxNzE4MzI4MTI4fQ.sAp8XpPZ0NCpc7bu7mr5BQfUbfFixW0-jkD4i8V6i3A
###
GET https://locpham.free.nf/img/staffitem.jpg
###
post http://localhost:3001/api/login
Content-Type: application/json

{
    "username":"locpham",
    "password":"123456"
}
